---
- name: Deploy Docker container
  hosts: localhost
  become: true
  tasks:
    - name: Stop running container
      shell: docker stop my-app || true && docker rm my-app || true

    - name: Run Docker container
      shell: docker run -d --name my-app -p 80:80 my-app
