---
- name: Deploy Go App Container
  hosts: localhost
  become: true
  tasks:
    - name: Stop running container
      shell: docker stop go-app || true && docker rm go-app || true

    - name: Run Docker container
      shell: docker run -d --name go-app -p 8080:8080 my-go-apis
